name: 'AL Object ID Ninja'
description: 'Warns about untracked object IDs or synchronizes consumption with Ninja backend'
inputs:
  exclude-field-ids:
    description: 'Skip checking table/table extension field IDs'
    required: false
    default: 'false'
  exclude-enum-value-ids:
    description: 'Skip checking enum/enum extension value IDs'
    required: false
    default: 'false'
runs:
  using: 'node24'
  main: 'dist/index.js'
